// <auto-generated />
using System;
using ChinaSoftRCW.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChinaSoftRCW.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200501141327_seedDataForTechStack")]
    partial class seedDataForTechStack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChinaSoftRCW.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("JobState")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ResidentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechStackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TechStackId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("ChinaSoftRCW.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectName = "Microsoft-BingFeedBack"
                        },
                        new
                        {
                            Id = 2,
                            ProjectName = "Microsoft-WrapStar"
                        },
                        new
                        {
                            Id = 3,
                            ProjectName = "Microsoft-Insider"
                        },
                        new
                        {
                            Id = 4,
                            ProjectName = "Microsoft-AD"
                        },
                        new
                        {
                            Id = 5,
                            ProjectName = "Microsoft-Azure"
                        });
                });

            modelBuilder.Entity("ChinaSoftRCW.Models.TechStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TechName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("TechStack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TechName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            TechName = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            TechName = "Java"
                        });
                });

            modelBuilder.Entity("ChinaSoftRCW.Models.Candidate", b =>
                {
                    b.HasOne("ChinaSoftRCW.Models.Project", "Project")
                        .WithMany("Candidates")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ChinaSoftRCW.Models.TechStack", "TechStack")
                        .WithMany("Candidates")
                        .HasForeignKey("TechStackId");
                });
#pragma warning restore 612, 618
        }
    }
}
